services:
  - type: web
    name: fintrack
    env: python
    buildCommand: "apt-get install -y tesseract-ocr tesseract-ocr-ind && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        value: fintrack-secret-2025